### ISSUE TITLE
请求增加Termux镜像源

### ISSUE THREAD

**Issue by 2096779623** [SDU-Mirrors/issues#1]
# 镜像名称
Termux

# 镜像简介
Termux 是一款Android 终端模拟器和 Linux 环境应用程序，无需 root 或设置即可直接运行。自动安装最小的基本系统 - 使用 APT 包管理器可以使用其他包。

# 镜像大小
15GB

# 同步方式
https://github.com/termux/termux-packages/wiki/How-to-mirror-the-official-repositories

**Comment by SadPencil** [comment]
感谢提议，这几天考虑部署一下

**Comment by SadPencil** [comment]
https://mirrors.sdu.edu.cn/termux/
已部署
