### ISSUE TITLE
Mirror requst: BioArchLinux

### ISSUE THREAD

**Issue by starsareintherose** [SDU-Mirrors/issues#2]
# Introduction

Name: BioArchLinux
Introduction: Arch Community for Biologists & Arch Repository for Biological Software
Official web: https://bioarchlinux.org/
Github Repo: https://github.com/BioArchLinux/Packages

# Mirror method
```
rsync -rtlivH bioarchlinux.org::sync/ destdir 
```

# Size

30G

**Comment by SadPencil** [comment]
I am glad to inform you that the mirror of BioArchLinux is now availble at [https://mirrors.sdu.edu.cn/bioarchlinux/](https://mirrors.sdu.edu.cn/bioarchlinux/) with a daily sync.

**Comment by starsareintherose** [comment]
thanks
