### ISSUE TITLE
Termux 软件镜像与主源不同步

### ISSUE THREAD

**Issue by licy183** [SDU-Mirrors/issues#4]
## 问题描述
目前镜像站的Termux软件源镜像与主源不同步。

## 可能的解决方式
按照 [Termux Package Wiki](https://github.com/termux/termux-packages/wiki/How-to-mirror-the-official-repositories) 给出的方式重新进行同步。

## 参考
termux/termux-packages#13977

**Comment by SadPencil** [comment]
`rsync -rtlvH --bwlimit=10240 --delete-after --delay-updates --safe-links --progress` 进程长时间卡住致后续同步任务停滞。已经手动杀掉进程重启同步服务。

**Comment by licy183** [comment]
已确认同步成功，感谢！
